namespace core.Models;

public class Data
{
  public int ID { get; set; }
  public float Data1 { get; set; }
  public float Data2 { get; set; }
  public float Data3 { get; set; }
  public float Data4 { get; set; }
  public float Data5 { get; set; }
  public float Data6 { get; set; }
  public float Data7 { get; set; }
  public float Data8 { get; set; }
  public float Data9 { get; set; }
  public float Data10 { get; set; }
  public float Data11 { get; set; }
  public float Data12 { get; set; }
  public float Data13 { get; set; }
  public float Data14 { get; set; }
  public float Data15 { get; set; }
  public float Data16 { get; set; }
  public float Data17 { get; set; }
  public float Data18 { get; set; }
  public float Data19 { get; set; }
  public float Data20 { get; set; }
  public float Data21 { get; set; }
  public float Data22 { get; set; }
  public float Data23 { get; set; }
  public float Data24 { get; set; }
  public float Data25 { get; set; }
  public float Data26 { get; set; }
  public float Data27 { get; set; }
  public float Data28 { get; set; }
  public float Data29 { get; set; }
  public float Data30 { get; set; }
  public float Data31 { get; set; }
  public float Data32 { get; set; }
  public float Data33 { get; set; }
  public float Data34 { get; set; }
  public float Data35 { get; set; }
  public float Data36 { get; set; }
  public float Data37 { get; set; }
  public float Data38 { get; set; }
  public float Data39 { get; set; }
  public float Data40 { get; set; }
  public float Data41 { get; set; }
  public float Data42 { get; set; }
  public float Data43 { get; set; }
  public float Data44 { get; set; }
  public float Data45 { get; set; }
  public float Data46 { get; set; }
  public float Data47 { get; set; }
  public float Data48 { get; set; }
  public float Data49 { get; set; }
  public float Data50 { get; set; }
  public float Data51 { get; set; }
  public float Data52 { get; set; }
  public float Data53 { get; set; }
  public float Data54 { get; set; }
  public float Data55 { get; set; }
  public float Data56 { get; set; }
  public float Data57 { get; set; }
  public float Data58 { get; set; }
  public float Data59 { get; set; }
  public float Data60 { get; set; }
  public float Data61 { get; set; }
  public float Data62 { get; set; }
  public float Data63 { get; set; }
  public float Data64 { get; set; }
  public float Data65 { get; set; }
  public float Data66 { get; set; }
  public float Data67 { get; set; }
  public float Data68 { get; set; }
  public float Data69 { get; set; }
  public float Data70 { get; set; }
  public float Data71 { get; set; }
  public float Data72 { get; set; }
  public float Data73 { get; set; }
  public float Data74 { get; set; }
  public float Data75 { get; set; }
  public float Data76 { get; set; }
  public float Data77 { get; set; }
  public float Data78 { get; set; }
  public float Data79 { get; set; }
  public float Data80 { get; set; }
  public float Data81 { get; set; }
  public float Data82 { get; set; }
  public float Data83 { get; set; }
  public float Data84 { get; set; }
  public float Data85 { get; set; }
  public float Data86 { get; set; }
  public float Data87 { get; set; }
  public float Data88 { get; set; }
  public float Data89 { get; set; }
  public float Data90 { get; set; }
  public float Data91 { get; set; }
  public float Data92 { get; set; }
  public float Data93 { get; set; }
  public float Data94 { get; set; }
  public float Data95 { get; set; }
  public float Data96 { get; set; }
  public float Data97 { get; set; }
  public float Data98 { get; set; }
  public float Data99 { get; set; }
  public float Data100 { get; set; }
  public float Data101 { get; set; }
  public float Data102 { get; set; }
  public float Data103 { get; set; }
  public float Data104 { get; set; }
  public float Data105 { get; set; }
  public float Data106 { get; set; }
  public float Data107 { get; set; }
  public float Data108 { get; set; }
  public float Data109 { get; set; }
  public float Data110 { get; set; }
  public float Data111 { get; set; }
  public float Data112 { get; set; }
  public float Data113 { get; set; }
  public float Data114 { get; set; }
  public float Data115 { get; set; }
  public float Data116 { get; set; }
  public float Data117 { get; set; }
  public float Data118 { get; set; }
  public float Data119 { get; set; }
  public float Data120 { get; set; }
  public float Data121 { get; set; }
  public float Data122 { get; set; }
  public float Data123 { get; set; }
  public float Data124 { get; set; }
  public float Data125 { get; set; }
  public float Data126 { get; set; }
  public float Data127 { get; set; }
  public float Data128 { get; set; }
  public float Data129 { get; set; }
  public float Data130 { get; set; }
  public float Data131 { get; set; }
  public float Data132 { get; set; }
  public float Data133 { get; set; }
  public float Data134 { get; set; }
  public float Data135 { get; set; }
  public float Data136 { get; set; }
  public float Data137 { get; set; }
  public float Data138 { get; set; }
  public float Data139 { get; set; }
  public float Data140 { get; set; }
  public float Data141 { get; set; }
  public float Data142 { get; set; }
  public float Data143 { get; set; }
  public float Data144 { get; set; }
  public float Data145 { get; set; }
  public float Data146 { get; set; }
  public float Data147 { get; set; }
  public float Data148 { get; set; }
  public float Data149 { get; set; }
  public float Data150 { get; set; }
  public float Data151 { get; set; }
  public float Data152 { get; set; }
  public float Data153 { get; set; }
  public float Data154 { get; set; }
  public float Data155 { get; set; }
  public float Data156 { get; set; }
  public float Data157 { get; set; }
  public float Data158 { get; set; }
  public float Data159 { get; set; }
  public float Data160 { get; set; }
  public float Data161 { get; set; }
  public float Data162 { get; set; }
  public float Data163 { get; set; }
  public float Data164 { get; set; }
  public float Data165 { get; set; }
  public float Data166 { get; set; }


}
